version: '3.0'
networks:
  backend-network: {}
volumes:
  database: {}
services:
  redis:
    image: redis:4.0
    networks:
    - backend-network
  database:
    image: mongo:4.0.3
    networks:
    - backend-network
    volumes:
    - database:/data/db
  backend:
    build: ../backend
    environment:
    - JWT_SECRET=REDACTED
    - AUTH_DATABASE_CONNECTION_STRING=mongodb://database:27017/emoji-app
    - LISTEN_PORT=8080
    networks:
    - backend-network
    ports:
    - 8081:8080
    depends_on:
    - database
  game-server:
    build: ../game-server
    environment:
    - JWT_SECRET=REDACTED
    - SOCKET_PORT=8080
    - HASHRING_PORT=7373
    - DOCKER_IMAGE_NAME=deployment_game-server
    - DOCKER_HASHRING_NETWORK_NAME=deployment_hashring-network
    - REDIS_URL=redis://redis:6379
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - backend-network
    depends_on:
    - redis
  proxy:
    build: ../proxy
    environment:
    - HASHRING_BASE_HOST=game-server
    - HASHRING_BASE_PORT=7373
    - API_HOST=backend
    - API_PORT=8080
    - PORT=8080
    networks:
    - backend-network
    ports:
    - 8080:8080
    depends_on:
    - game-server
    - backend
